kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    tags: latest
    repo: registry.geekfor.science/scienzabotb
    #  from_secret: docker_registry
  commands:
  - go build .
- name: static analysis
  image: plugins/docker
  settings:
    tags: latest
    repo:
      from_secret: docker_registry
  commands:
  - golint .
  - go vet .
  - maligned ./...
