kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    tags: latest
    repo: pandry/scienzabotb
  commands:
  - go build .
- name: static analysis
  image: plugins/docker
  settings:
    tags: latest
    repo: pandry/scienzabotb
  commands:
  - golint .
  - go vet .
  - maligned ./...
