kind: pipeline
name: default

workspace:
  base: /go
  path: src/scienzabot

steps:
- name: test
  image: golang
  commands:
  - go get
  - go test
- name: build
  image: golang
  commands:
  - go get
  - go build
- name: static analysis
  image: golang
  commands:
  - go get
  - golint .
  - go vet .
  - maligned ./...
