kind: pipeline
name: default

workspace:
  base: /go
  path: src/scienzabot

steps:
- name: Running Unit Tests
  image: golang
  commands:
  - go get
  - go test ./...
    
- name: Doing Static Analysis
  image: golang
  commands:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mdempsky/maligned
  - golint .
  - go vet .
  - maligned ./...
  
- name: Statically compiling the solution
  image: golang
  commands:
  - CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static"' .
  
- name: Solution executable upload
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: production_server_address
    username: 
      from_secret: production_server_username
    key: 
      from_secret: production_server_privatekey
    port: 22
    target: /root
    source: ./scienzabot

- name: Building and tagging the container solution
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: production_server_address
    username: 
      from_secret: production_server_username
    key: 
      from_secret: production_server_privatekey
    port: 22
    script:
      - mv -f scienzabot scienza/scienzabot
      - cd scienza/ 
      - docker image tag $(docker build . | tail -n 1 | awk ' { print $3 } ') scienzabot
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

- name: Replacing the running version with the new one
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: production_server_address
    username: 
      from_secret: production_server_username
    key: 
      from_secret: production_server_privatekey
    port: 22
    secrets: [ telegram_bot_api_token ]
    envs: [ telegram_bot_api_token ]
    script:
      - docker rename scienzabot scienzabotold
      - docker stop scienzabotold
      - cp $(docker volume inspect scienzabot | grep Mountpoint | awk {' print $2 '} | cut -c 2- | rev | cut -c 3- | rev)/sqlite db_backup_$(date +%y-%m-%d_%H:%M:%S).sqlite
      - docker run --name=scienzabot --env="TELEGRAM_TOKEN=$telegram_bot_api_token" --volume="scienzabot:/db" --restart=unless-stopped --detach=true scienzabot:latest /scienzabot -database /db/sqlite -vv
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
