kind: pipeline
name: default

workspace:
  base: /go
  path: src/scienzabot

steps:
- name: Running Unit Tests
  image: golang
  commands:
  - go get
  - go test ./...
    
- name: Doing Static Analysis
  image: golang
  commands:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mdempsky/maligned
  - go get github.com/fzipp/gocyclo
  - golint .
  - go vet .
  - maligned ./...
  - go get github.com/Pandry/gocol
  - (echo "Complexity Package Function File Row Column" && gocyclo -over 15 . | sed "s/:/ /g" ) | gocol -c " " -d " " -t 4 -p 2
  when:
    branch:
      exclude:
        - prod
  
- name: Statically compiling the solution
  image: golang
  commands:
  - CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static"' .
  when:
    branch:
      - prod
    event:
      exclude:
        - pull_request
  
- name: Solution executable upload
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: production_server_address
    username: 
      from_secret: production_server_username
    key: 
      from_secret: production_server_privatekey
    port: 22
    target: /root
    source: ./scienzabot
  when:
    branch:
      - prod
    event:
      exclude:
        - pull_request

- name: Building and tagging the container solution
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: production_server_address
    username: 
      from_secret: production_server_username
    key: 
      from_secret: production_server_privatekey
    port: 22
    script:
      - mv -f scienzabot scienza/scienzabot
      - cd scienza/ 
      - docker image tag $(docker build . | tail -n 1 | awk ' { print $3 } ') scienzabot
  when:
    branch:
      - prod
    event:
      exclude:
        - pull_request

- name: Replacing the running version with the new one
  image: appleboy/drone-ssh
  environment:
    TELEGRAM_BOT_API_TOKEN:
      from_secret: telegram_bot_api_token
  settings:
    host:
      from_secret: production_server_address
    username: 
      from_secret: production_server_username
    key: 
      from_secret: production_server_privatekey
    port: 22
    envs: [TELEGRAM_BOT_API_TOKEN]
    script:
      - docker stop scienzabot
      - docker rename scienzabot scienzabotold
      - cp $(docker volume inspect scienzabot | grep Mountpoint | awk {' print $2 '} | cut -c 2- | rev | cut -c 3- | rev)/sqlite db_backup_$(date +%y-%m-%d_%H:%M:%S).sqlite
      - docker run --name=scienzabot --env="TELEGRAM_TOKEN=$TELEGRAM_BOT_API_TOKEN" --volume="scienzabot:/db" --restart=unless-stopped --detach=true scienzabot:latest /scienzabot -database /db/sqlite -vv
      - docker rm scienzabotold
  when:
    branch:
      - prod
    event:
      exclude:
        - pull_request
