kind: pipeline
name: default

steps:
- name: build
  image: pandry/scienzabotb
  commands:
  - cp -r $(pwd) $GOPATH/src/scienzabot/ 
  - go build .
- name: static analysis
  image: pandry/scienzabotb
  commands:
  - golint .
  - go vet .
  - maligned ./...
