kind: pipeline
name: default

workspace:
  base: /go
  path: src/scienzabot

steps:
- name: test
  image: golang
  commands:
  - go get
  - go test ./...
- name: build
  image: golang
  commands:
  - go build
- name: static analysis
  image: golang
  commands:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mdempsky/maligned
  - golint .
  - go vet .
  - maligned ./...
